version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.5
    working_directory: ~/devon
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
      - run: yarn build
  ios:
    macos:
      xcode: "10.1"
    working_directory: ~/devon/packages/mobile
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout

